%YAML:1.0


image_topic: "/camera/infra1/image_rect_raw"
output_path: "/home/huai/output"
#camera calibration 
model_type: PINHOLE
camera_name: camera
image_width: 640
image_height: 480
distortion_parameters:
   k1: 0.005403441137290043
   k2: -0.004430036145734217
   p1: 2.3253828590255113e-05
   p2: -1.4587176183337531e-05
projection_parameters:
   fx: 380.7717651612202
   fy: 380.92158674730956
   cx: 317.60534045716395
   cy: 239.85147774070316
   
#additional transform for bais
initialRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.559231,  -0.825915,  0.0715889,
          0.820932,   0.563738,  0.0909351,
          -0.115462,  0.00791596, 0.99328]
   # data: [0.5727,   -0.8194,   -0.0242,
   #        0.8197,    0.5729,   -0.0001,
   #        0.0139,   -0.0198,    0.9997]

#Translation from first body frame to world frame
initialTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [-19.2952, -32.5391, -302.446]
   # data: [9.6821, -4.6821, -247.1419]
   
#Rotation from camera frame to imu frame, imu^R_cam
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.,    0.,   1.,
          -1.,    0.,    0.,
          0.,    -1.,    0.]
#Translation from camera frame to imu frame, imu^T_cam
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [0.0, 0.0, 0.0]

# optimization parameters
iterations: 2
per_inliers: 8
savefile: 0
threshold: 30
lamda: 0.1745
show: 1

